-- TED logical schema reference from supplied Oracle DDL (2026-09-16).
-- NOT a deployment migration. Existing objects must not be recreated.
-- Physical storage clauses omitted. Sequence definitions/START WITH values
-- were not supplied: existing *_SEQ sequences are required by the triggers.
-- The application only SELECTs from SAP_* tables.

CREATE TABLE TED.UGO_KOR (
ID        INTEGER                             NOT NULL,
  AD_SIFRA  VARCHAR2(200 BYTE)                  NOT NULL,
  IME       VARCHAR2(100 BYTE),
  STATUS    VARCHAR2(1 BYTE),
  DATPRI    DATE,
  DATIZM    DATE
);

CREATE TABLE TED.UGO_EVID (
ID               INTEGER                      NOT NULL,
  ID_SAP_UGOVOR    INTEGER                      NOT NULL,
  ID_UGO_ORG       INTEGER                      NOT NULL,
  IME              VARCHAR2(100 BYTE)           NOT NULL,
  TELEFON          VARCHAR2(100 BYTE),
  EMAIL            VARCHAR2(100 BYTE),
  STATUS           VARCHAR2(1 BYTE),
  DATPRI           DATE,
  DATIZM           DATE,
  ID_UGO_DOB_LICA  INTEGER
);

CREATE TABLE TED.UGO_KOR_ROLE (
ID          INTEGER                           NOT NULL,
  ID_UGO_KOR  INTEGER                           NOT NULL,
  ID_UGO_ORG  INTEGER                           NOT NULL,
  STATUS      VARCHAR2(1 BYTE),
  DATPRI      DATE,
  DATIZM      DATE
);

CREATE TABLE TED.UGO_ORG (
ID         INTEGER                            NOT NULL,
  SIFRA      VARCHAR2(10 BYTE)                  NOT NULL,
  SIFRA_CIR  VARCHAR2(10 BYTE),
  NAZIV      VARCHAR2(200 BYTE)                 NOT NULL,
  NAZIV_CIR  VARCHAR2(200 BYTE),
  STATUS     VARCHAR2(1 BYTE),
  DATPRI     DATE,
  DATIZM     DATE
);

CREATE TABLE TED.UGO_DOB_LICA (
ID                    INTEGER                 NOT NULL,
  ID_SAP_DOBAVLJAC      INTEGER                 NOT NULL,
  IME                   VARCHAR2(100 BYTE),
  RADNO_MESTO           VARCHAR2(200 BYTE),
  TELEFON               VARCHAR2(100 BYTE),
  EMAIL                 VARCHAR2(100 BYTE),
  ID_UGO_DOB_LICA_ROLA  INTEGER,
  STATUS                VARCHAR2(1 BYTE),
  DATPRI                DATE,
  DATZM                 DATE
);

CREATE TABLE TED.UGO_DOB_LICA_ROLE (
ID      INTEGER,
  NAZIV   VARCHAR2(100 BYTE)                    NOT NULL,
  STATUS  VARCHAR2(1 BYTE),
  DATPRI  DATE,
  DATZM   DATE
);

CREATE TABLE TED.SAP_DOBAVLJACI (
ID          INTEGER                           NOT NULL,
  SIFRA       VARCHAR2(20 BYTE)                 NOT NULL,
  NAZIV       VARCHAR2(200 BYTE)                NOT NULL,
  WEB_PORTAL  VARCHAR2(4000 BYTE)
);

CREATE TABLE TED.SAP_ODGLICA (
ID              INTEGER                       NOT NULL,
  ID_SAP_UGOVORI  INTEGER                       NOT NULL,
  ODG_ZAP         VARCHAR2(8 BYTE)              NOT NULL,
  NAZIV_ODG_ZAP   VARCHAR2(100 BYTE)            NOT NULL,
  R_BR            NUMBER                        NOT NULL
);

CREATE TABLE TED.SAP_UGOVORI (
ID INTEGER NOT NULL,
    GODINA VARCHAR2(4 BYTE),
    BR_UGOVOR VARCHAR2(10 BYTE) NOT NULL,
    UGOVOR_DMS VARCHAR2(100 BYTE),
    JN VARCHAR2(20 BYTE),
    BR_POZ_PLANA VARCHAR2(20 BYTE),
    PREDMET_UGOVORA VARCHAR2(300 BYTE),
    ID_SAP_DOBAVLJAC INTEGER,
    OTVOREN_UG VARCHAR2(10 BYTE),
    ZZN VARCHAR2(10 BYTE),
    POCETAK_UG DATE,
    KRAJ_UG DATE,
    VREDNOST_UG NUMBER(15,2),
    VALUTA_UG VARCHAR2(10 BYTE),
    KURS_UG NUMBER(9,5),
    KOM_GRUPA VARCHAR2(5 BYTE),
    M_BR_KOMERC VARCHAR2(20 BYTE),
    NAZ_KOMERC VARCHAR2(40 BYTE),
    GR_NAB VARCHAR2(5 BYTE),
    NAZIV_GR_PLAN VARCHAR2(40 BYTE),
    VRS_PRED VARCHAR2(400 BYTE)
);

ALTER TABLE TED.UGO_KOR ADD PRIMARY KEY (ID);
ALTER TABLE TED.UGO_EVID ADD PRIMARY KEY (ID);
ALTER TABLE TED.UGO_KOR_ROLE ADD PRIMARY KEY (ID);
ALTER TABLE TED.UGO_ORG ADD PRIMARY KEY (ID);
ALTER TABLE TED.UGO_DOB_LICA ADD PRIMARY KEY (ID);
ALTER TABLE TED.UGO_DOB_LICA_ROLE ADD PRIMARY KEY (ID);
ALTER TABLE TED.SAP_DOBAVLJACI ADD PRIMARY KEY (ID);
ALTER TABLE TED.SAP_ODGLICA ADD PRIMARY KEY (ID);
ALTER TABLE TED.SAP_UGOVORI ADD PRIMARY KEY (ID);
ALTER TABLE TED.UGO_KOR ADD UNIQUE (AD_SIFRA);
ALTER TABLE TED.UGO_ORG ADD UNIQUE (SIFRA);
ALTER TABLE TED.SAP_DOBAVLJACI ADD UNIQUE (SIFRA);
ALTER TABLE TED.SAP_UGOVORI ADD UNIQUE (BR_UGOVOR, BR_POZ_PLANA);
ALTER TABLE TED.UGO_EVID ADD UNIQUE (ID_SAP_UGOVOR, ID_UGO_ORG);
ALTER TABLE TED.UGO_EVID ADD FOREIGN KEY (ID_SAP_UGOVOR) REFERENCES TED.SAP_UGOVORI (ID);
ALTER TABLE TED.UGO_EVID ADD FOREIGN KEY (ID_UGO_ORG) REFERENCES TED.UGO_ORG (ID);
ALTER TABLE TED.UGO_EVID ADD FOREIGN KEY (ID_UGO_DOB_LICA) REFERENCES TED.UGO_DOB_LICA (ID);
ALTER TABLE TED.UGO_KOR_ROLE ADD FOREIGN KEY (ID_UGO_KOR) REFERENCES TED.UGO_KOR (ID);
ALTER TABLE TED.UGO_KOR_ROLE ADD FOREIGN KEY (ID_UGO_ORG) REFERENCES TED.UGO_ORG (ID);
ALTER TABLE TED.UGO_DOB_LICA ADD FOREIGN KEY (ID_SAP_DOBAVLJAC) REFERENCES TED.SAP_DOBAVLJACI (ID);
ALTER TABLE TED.UGO_DOB_LICA ADD FOREIGN KEY (ID_UGO_DOB_LICA_ROLA) REFERENCES TED.UGO_DOB_LICA_ROLE (ID);
ALTER TABLE TED.SAP_UGOVORI ADD FOREIGN KEY (ID_SAP_DOBAVLJAC) REFERENCES TED.SAP_DOBAVLJACI (ID);
ALTER TABLE TED.SAP_ODGLICA ADD FOREIGN KEY (ID_SAP_UGOVORI) REFERENCES TED.SAP_UGOVORI (ID);

CREATE OR REPLACE TRIGGER TED.UGO_KOR
BEFORE INSERT ON TED.UGO_KOR
FOR EACH ROW
BEGIN
  SELECT TED.UGO_KOR_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.UGO_EVID
BEFORE INSERT ON TED.UGO_EVID
FOR EACH ROW
BEGIN
  SELECT TED.UGO_EVID_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.UGO_KOR_ROLE
BEFORE INSERT ON TED.UGO_KOR_ROLE
FOR EACH ROW
BEGIN
  SELECT TED.UGO_KOR_ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.UGO_ORG
BEFORE INSERT ON TED.UGO_ORG
FOR EACH ROW
BEGIN
  SELECT TED.UGO_ORG_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.UGO_DOB_LICA
BEFORE INSERT ON TED.UGO_DOB_LICA
FOR EACH ROW
BEGIN
  SELECT TED.UGO_DOB_LICA_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.UGO_DOB_LICA_ROLE
BEFORE INSERT ON TED.UGO_DOB_LICA_ROLE
FOR EACH ROW
BEGIN
  SELECT TED.UGO_DOB_LICA_ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.SAP_DOBAVLJACI
BEFORE INSERT ON TED.SAP_DOBAVLJACI
FOR EACH ROW
BEGIN
  SELECT TED.SAP_DOBAVLJACI_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.SAP_ODGLICA_TRG
BEFORE INSERT ON TED.SAP_ODGLICA
FOR EACH ROW
BEGIN
  SELECT TED.SAP_ODGLICA_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TED.SAP_UGOVORI
BEFORE INSERT ON TED.SAP_UGOVORI
FOR EACH ROW
BEGIN
  SELECT TED.SAP_UGOVORI_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
