-- Optional bootstrap for an EMPTY Oracle 12c+ schema. Do not run against existing tables.
CREATE TABLE sap_dobavljaci (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sifra VARCHAR2(20) NOT NULL UNIQUE,
    naziv VARCHAR2(200) NOT NULL,
    web_portal VARCHAR2(4000)
);

COMMENT ON COLUMN sap_dobavljaci.web_portal IS 'Web portal dobavljača';

CREATE TABLE sap_ugovori (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    godina VARCHAR2(4),
    br_ugovor VARCHAR2(10) NOT NULL,
    ugovor_dms VARCHAR2(100),
    jn VARCHAR2(20),
    br_poz_plana VARCHAR2(20),
    predmet_ugovora VARCHAR2(300),
    id_sap_dobavljac NUMBER(10) REFERENCES sap_dobavljaci(id),
    otvoren_ug VARCHAR2(10),
    zzn VARCHAR2(10),
    pocetak_ug DATE,
    kraj_ug DATE,
    vrednost_ug NUMBER(15,2),
    valuta_ug VARCHAR2(10),
    kurs_ug NUMBER(9,5),
    kom_grupa VARCHAR2(5),
    m_br_komerc VARCHAR2(20),
    naz_komerc VARCHAR2(40),
    gr_nab VARCHAR2(5),
    naziv_gr_plan VARCHAR2(40),
    vrs_pred VARCHAR2(400)
);

CREATE UNIQUE INDEX sap_ugovori_uk ON sap_ugovori (br_ugovor, br_poz_plana);

CREATE TABLE sap_odglica (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_sap_ugovori NUMBER(10) NOT NULL REFERENCES sap_ugovori(id),
    odg_zap VARCHAR2(8) NOT NULL,
    naziv_odg_zap VARCHAR2(100) NOT NULL,
    r_br NUMBER(10) NOT NULL
);

CREATE TABLE ugo_org (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sifra VARCHAR2(10) NOT NULL UNIQUE,
    sifra_cir VARCHAR2(10),
    naziv VARCHAR2(200) NOT NULL,
    naziv_cir VARCHAR2(200),
    status CHAR(1),
    datpri TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datizm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ugo_dob_lica_role (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    naziv VARCHAR2(100) NOT NULL,
    status CHAR(1),
    datpri TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datzm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ugo_kor (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ad_sifra VARCHAR2(200) NOT NULL UNIQUE,
    sifra VARCHAR2(200) NOT NULL UNIQUE,
    lozinka VARCHAR2(200) NOT NULL UNIQUE,
    ime VARCHAR2(100),
    status CHAR(1),
    datpri TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datizm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ugo_kor_role (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_ugo_kor NUMBER(10) NOT NULL REFERENCES ugo_kor(id),
    id_ugo_org NUMBER(10) NOT NULL REFERENCES ugo_org(id),
    status CHAR(1),
    datpri TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datizm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ugo_dob_lica (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_sap_dobavljac NUMBER(10) NOT NULL REFERENCES sap_dobavljaci(id),
    id_ugo_org NUMBER(10) NOT NULL REFERENCES ugo_org(id),
    ime VARCHAR2(100),
    radno_mesto VARCHAR2(200),
    telefon VARCHAR2(100),
    email VARCHAR2(100),
    id_ugo_dob_lica_rola NUMBER(10) REFERENCES ugo_dob_lica_role(id),
    status CHAR(1),
    datpri TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datzm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ugo_evid (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_sap_ugovor NUMBER(10) NOT NULL REFERENCES sap_ugovori(id),
    id_ugo_org NUMBER(10) NOT NULL REFERENCES ugo_org(id),
    ime VARCHAR2(100) NOT NULL,
    telefon VARCHAR2(100),
    email VARCHAR2(100),
    status CHAR(1),
    datpri TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datizm TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_ugo_dob_lica NUMBER(10) REFERENCES ugo_dob_lica(id),
    UNIQUE (id_sap_ugovor, id_ugo_org)
);
CREATE OR REPLACE VIEW sap_ugovori_v AS
SELECT 
    u.id AS ugovor_id,
    u.godina,
    u.br_ugovor,
    u.ugovor_dms,
    u.jn,
    u.br_poz_plana,
    u.predmet_ugovora,
    u.otvoren_ug,
    u.pocetak_ug,
    u.kraj_ug,
    u.naz_komerc,
    u.gr_nab,
    u.naziv_gr_plan,
    u.vrs_pred,
    d.naziv AS dob_naziv,
    d.web_portal AS dob_web,
    -- r_br = 1
    MAX(CASE WHEN o.r_br = 1 THEN o.odg_zap END)        AS odg_zap_1,
    MAX(CASE WHEN o.r_br = 1 THEN o.naziv_odg_zap END)  AS odg_naziv_1,
    -- r_br = 2
    MAX(CASE WHEN o.r_br = 2 THEN o.odg_zap END)        AS odg_zap_2,
    MAX(CASE WHEN o.r_br = 2 THEN o.naziv_odg_zap END)  AS odg_naziv_2,
    -- r_br = 3
    MAX(CASE WHEN o.r_br = 3 THEN o.odg_zap END)        AS odg_zap_3,
    MAX(CASE WHEN o.r_br = 3 THEN o.naziv_odg_zap END)  AS odg_naziv_3,
    -- r_br = 4
    MAX(CASE WHEN o.r_br = 4 THEN o.odg_zap END)        AS odg_zap_4,
    MAX(CASE WHEN o.r_br = 4 THEN o.naziv_odg_zap END)  AS odg_naziv_4
FROM sap_ugovori u
LEFT JOIN sap_dobavljaci d 
    ON d.id = u.id_sap_dobavljac
LEFT JOIN sap_odglica o 
    ON o.id_sap_ugovori = u.id
GROUP BY 
    u.id, u.godina, u.br_ugovor, u.ugovor_dms, u.jn, u.br_poz_plana,
    u.predmet_ugovora, u.otvoren_ug, u.pocetak_ug, u.kraj_ug, 
    u.naz_komerc, u.gr_nab, u.naziv_gr_plan, u.vrs_pred,
    d.naziv, d.web_portal
ORDER BY u.id;
